<?php
// Do not edit this file.
// Anything you might want to do here should be done in app/
//

require __DIR__ .'/../inc/setup.php';
require __DIR__ .'/../inc/widgets.php';

/*Old Framework*/
$registrar = require __DIR__.'/../app/load.php';
$registrar->register();


